package com.wdxxl.common.model;

public class AuthorityUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_user.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_user.username
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_user.password
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_user.display_name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String displayName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_user.is_active
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private Integer isActive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_user.is_admin
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private Integer isAdmin;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_user.id
	 * @return  the value of authority_user.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_user.id
	 * @param id  the value for authority_user.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_user.username
	 * @return  the value of authority_user.username
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_user.username
	 * @param username  the value for authority_user.username
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_user.password
	 * @return  the value of authority_user.password
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_user.password
	 * @param password  the value for authority_user.password
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_user.display_name
	 * @return  the value of authority_user.display_name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getDisplayName() {
		return displayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_user.display_name
	 * @param displayName  the value for authority_user.display_name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_user.is_active
	 * @return  the value of authority_user.is_active
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public Integer getIsActive() {
		return isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_user.is_active
	 * @param isActive  the value for authority_user.is_active
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_user.is_admin
	 * @return  the value of authority_user.is_admin
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public Integer getIsAdmin() {
		return isAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_user.is_admin
	 * @param isAdmin  the value for authority_user.is_admin
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setIsAdmin(Integer isAdmin) {
		this.isAdmin = isAdmin;
	}
}