package com.wdxxl.common.model;

public class AuthorityRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_role.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_role.name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_role.comments
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String comments;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_role.id
	 * @return  the value of authority_role.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_role.id
	 * @param id  the value for authority_role.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_role.name
	 * @return  the value of authority_role.name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_role.name
	 * @param name  the value for authority_role.name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_role.comments
	 * @return  the value of authority_role.comments
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_role.comments
	 * @param comments  the value for authority_role.comments
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

}