package com.wdxxl.common.model;

public class AuthorityResource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_resource.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_resource.name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_resource.url
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_resource.is_visible
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private Integer isVisible;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_resource.type
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_resource.pid
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_resource.sort_order
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private Integer sortOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authority_resource.comments
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String comments;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_resource.id
	 * @return  the value of authority_resource.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_resource.id
	 * @param id  the value for authority_resource.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_resource.name
	 * @return  the value of authority_resource.name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_resource.name
	 * @param name  the value for authority_resource.name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_resource.url
	 * @return  the value of authority_resource.url
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_resource.url
	 * @param url  the value for authority_resource.url
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_resource.is_visible
	 * @return  the value of authority_resource.is_visible
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public Integer getIsVisible() {
		return isVisible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_resource.is_visible
	 * @param isVisible  the value for authority_resource.is_visible
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setIsVisible(Integer isVisible) {
		this.isVisible = isVisible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_resource.type
	 * @return  the value of authority_resource.type
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_resource.type
	 * @param type  the value for authority_resource.type
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_resource.pid
	 * @return  the value of authority_resource.pid
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_resource.pid
	 * @param pid  the value for authority_resource.pid
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_resource.sort_order
	 * @return  the value of authority_resource.sort_order
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public Integer getSortOrder() {
		return sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_resource.sort_order
	 * @param sortOrder  the value for authority_resource.sort_order
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authority_resource.comments
	 * @return  the value of authority_resource.comments
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authority_resource.comments
	 * @param comments  the value for authority_resource.comments
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}
}