package com.wdxxl.common.model;

public class Student {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.age
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.address
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.id
	 * @return  the value of student.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.id
	 * @param id  the value for student.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.name
	 * @return  the value of student.name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.name
	 * @param name  the value for student.name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.age
	 * @return  the value of student.age
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.age
	 * @param age  the value for student.age
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.address
	 * @return  the value of student.address
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.address
	 * @param address  the value for student.address
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setAddress(String address) {
		this.address = address;
	}
}