package com.wdxxl.common.model;

import java.util.List;
/**
 * Add List<Student> students;
 * @author wdxxl
 */
public class Teacher {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.age
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.course
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	private String course;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.id
	 * @return  the value of teacher.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.id
	 * @param id  the value for teacher.id
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.name
	 * @return  the value of teacher.name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.name
	 * @param name  the value for teacher.name
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.age
	 * @return  the value of teacher.age
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.age
	 * @param age  the value for teacher.age
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.course
	 * @return  the value of teacher.course
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public String getCourse() {
		return course;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.course
	 * @param course  the value for teacher.course
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	public void setCourse(String course) {
		this.course = course;
	}

	private List<Student> students;
    
	public List<Student> getStudents() {
		return students;
	}

	public void setStudents(List<Student> students) {
		this.students = students;
	}


}