package com.wdxxl.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wdxxl.common.model.AuthorityUser;
import com.wdxxl.common.model.AuthorityUserExample;

public interface AuthorityUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_user
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int countByExample(AuthorityUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_user
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int deleteByExample(AuthorityUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_user
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_user
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int insert(AuthorityUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_user
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int insertSelective(AuthorityUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_user
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	List<AuthorityUser> selectByExample(AuthorityUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_user
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	AuthorityUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_user
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AuthorityUser record,
			@Param("example") AuthorityUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_user
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int updateByExample(@Param("record") AuthorityUser record,
			@Param("example") AuthorityUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_user
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int updateByPrimaryKeySelective(AuthorityUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_user
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int updateByPrimaryKey(AuthorityUser record);

	//Manually
    List<AuthorityUser> getUserByRoleName(@Param(value="roleName")String roleName, @Param(value="isActive")Integer status);

}