package com.wdxxl.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wdxxl.common.model.AuthorityRole;
import com.wdxxl.common.model.AuthorityRoleExample;

public interface AuthorityRoleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_role
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int countByExample(AuthorityRoleExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_role
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int deleteByExample(AuthorityRoleExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_role
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_role
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int insert(AuthorityRole record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_role
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int insertSelective(AuthorityRole record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_role
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	List<AuthorityRole> selectByExample(AuthorityRoleExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_role
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	AuthorityRole selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_role
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AuthorityRole record,
			@Param("example") AuthorityRoleExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_role
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int updateByExample(@Param("record") AuthorityRole record,
			@Param("example") AuthorityRoleExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_role
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int updateByPrimaryKeySelective(AuthorityRole record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authority_role
	 * @mbggenerated  Thu Jun 19 00:46:09 CST 2014
	 */
	int updateByPrimaryKey(AuthorityRole record);
	List<AuthorityRole> getRoleCode(Integer userId) throws Exception;
    AuthorityRole getRoleById(Integer id)throws Exception;
    AuthorityRole getRoleByName(String name) throws Exception;
    List<AuthorityRole> getRoleByUserId(Integer userid) throws Exception;

    //void update(Role role) throws Exception;
    //int delUserRoleBy(UserRole userRole)throws Exception;
    //int insertUserRole(UserRole userRole)throws Exception;
}